version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "rails-reviewers"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
      # parser shall be same version as Ruby
      - dependency-name: "parser"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"