version: "3"
services:
  mysql:
    image: mysql/mysql-server:5.7
    platform: linux/amd64
    command: ["--bind-address=0.0.0.0"]
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/tmp/db:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    platform: linux/arm64/v8
    environment:
      MYSQL_USERNAME: app
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - .:/app
      - awesome_events_bundle:/app/vendor/bundle
      - awesome_events_node_modules:/app/node_modules

volumes:
  mysql-data:
    driver: local
  awesome_events_bundle:
    driver: local
  awesome_events_node_modules:
    driver: local